### ISSUE TITLE
Decide on testing approach

### ISSUE THREAD

**Issue by jasoncrawford** [objectivists/translations#7]
Creating this so we have a thread to discuss test issues.

* Do we require tests with every pull request? (I vote yes)
* Do we do unit test? Functional tests? Integration tests?
* How do we do test data? Rails fixtures? Factories? Do we use a gem like Factory Girl?
* Any general thoughts on how thorough to be, how granular, etc.

**Comment by jasoncrawford** [comment]
Tentative decisions:

* Include tests with every pull request
* Tests should cover all key requirements (this is more important than code coverage)
* Use both unit and functional tests, especially functional for our purposes; integration tests probably not needed
* Use Rails fixtures and/or Factory Girl; maybe in combination as seems appropriate

**Comment by dominicbertolino** [comment]
I was initially leaning towards using just fixtures due to their builtin support. However, after looking more into it I’m learning more towards Factory Girl. I don’t have much experience with either but from what I gathered with fixtures, the test data initialized is uniform between unrelated tests. This can create confusing coupling between seemingly unrelated tests. For example, you might change the test data for one tests only to realize other, "unrelated" tests were making assumptions about the shared data. Factory Girl seems to nicely handle this concern. 

Overall, I’m still fine with using whatever tool works best and fixtures may be more ideal in some cases. However, for some of the initial setup code I’m going to add in Factory Girl support as it works nicely with the tests.

**Comment by jasoncrawford** [comment]
Sure, sounds good. I think a very small number of fixtures could be helpful. But do it however seems best to you.

@timcheadle let us know if you have opinions/guidance here!

**Comment by timcheadle** [comment]
I've used minitest and rspec extensively, as well as fixtures and FactoryGirl. Since you're new to Rails @dominicbertolino, I'd recommend rspec. It's another DSL to learn, but frankly the community support and documentation FAR exceeds minitest.

I personally like minitest, but fixtures are a bit burdensome to work with unless you design them properly. FactoryGirl is much easier to define and use.

That said, FactoryGirl does result in slower tests, as records are created for every test case instead of loaded in bulk at the outset. I don't think test performance is a primary concern for this app, though.

**Comment by dominicbertolino** [comment]
Great, that was my impression about Factory Girl vs fixtures. As for rspec, I'll check it out more. My initial impression was to favor minitest as it is more bare-bones and I couldn't tell if learning rspec's DSL provided much gain.
